book:
  chapters:
    - index.qmd
    - sec-why-statistics.qmd
    - part: Studiedesign
      chapters:
        - sec-measurement.qmd
        - sec-design.qmd
    - part: Deskriptiv statistikk
      chapters:
        - sec-jamovi.qmd
        - sec-descriptive.qmd
        - sec-associations.qmd
    - part: Inferensiell statistikk
      chapters:
        - sec-inferential.qmd
    - sec-epilogue.qmd
    - sec-references.qmd
