<!-- \placetextbox{0.26}{0.06}{\scriptsize{©2025 D.R. Foxcroft and D.J. Navarro,}} -->
<!-- \placetextbox{0.195}{0.05}{\scriptsize{CC BY-SA 4.0}} -->
<!-- \placetextbox{0.70}{0.06}{\scriptsize{\url{https://doi.org/10.11647/OBP.0333.17}}} -->

# Etterord {.unnumbered}

> *"Begin at the beginning", the King said, very gravely, "and go on till you come to the end: then stop"*\
> -- Lewis Carroll, *Alice in Wonderland*

Som nevnt i forordet, er denne læreboken en betydelig forkortet versjon av en bok skrevet for et kurs som krevde et firedels semesters arbeid, altså 7,5 studiepoeng. Fra over 500 sider har vi kuttet og komprimert materialet ned til omtrent 170 sider. Alle disse er omarbeidet, og i tilleg er 30 sider skrevet spesifikt for denne utgaven, hovedsakelig i kapitlene om måling og forskningsdesign. Dette betyr naturligvis at mange detaljer, og faktisk også mye som ikke er detaljer, har blitt utelatt for å holde omfanget håndterbart. Skulle du ønske å lese mer om en metode, kanskje særlig hvis du planlegger å benytte den i en fremtidig masteroppgave, vil du finne et vell av ytterligere informasjon og detaljer i den originale utgaven av boken [@navarro2025].

Den største unnlatelsessynden i denne boken er at vi ikke har adressert alle de matematiske antagelsene som ligger til grunn for analysemetodene i inferensiell statistikk. Dette er for å ikke overvelde studenter med lite matematisk forkunnskap. Jeg tror mange er lettet over at de slipper å lære seg å uttale ord som "heteroskedastisitet" eller å vurdere om residualene er normalfordelte. Jeg har vektlagt de viktigste antagelsene med størst påvirkning på resultatenes validitet, nemlig at trekkene i utvalget er tilfeldige og uavhengige av hverandre.

Noe av hovedpoenget med å skrive denne boka er å gjøre alt materialet relevant for lærere i skolen. Dette arbeidet er langt fra i mål. Til fremtidige utgaver håper jeg å ha flere og bedre eksempler, og at eksemplene samlet sett viser noe av bredden i kvantitativ forskning på utdanningsfeltet. Jeg ønsker å inkludere egne kapitler om store internasjonale undersøkelser, nasjonale prøver, kartleggingsprøver og summative vurderinger i skolen, og jeg ønsker at dette går på bekostning av noe av teorien i de senere delene. Målet er at alle lærere skal tenke "jeg er jommen glad jeg har lært dette" når de kommer til slutten av boka.